theme: jekyll-theme-cayman
baseurl: /techblog
url: https://europepmc.github.io
title: Europe PMC Tech Blog
description: Techy stuff from Europe PMC
google_analytics: UA-114538088-1
collections:
  blog_categories:
    output: true
    permalink: /categories/:name/
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
twitter_username: EuropePMC_news
title_image: /techblog/images/epmc-techblog.png