theme: jekyll-theme-cayman
baseurl: /techblog
url: https://europepmc.github.io
title: Europe PMC Tech Blog
description: techy stuff from Europe PMC
collections:
  blog_categories:
    output: true
    permalink: /categories/:name/
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
